FROM ubuntu

RUN apt-get update
RUN apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_16.x | bash -
RUN apt-get upgrade -y
RUN apt-get install -y nodejs

COPY . .

RUN cd vite-project

RUN npm install

ENTRYPOINT [ "npm run dev" ]